blog/urls.py
from django.urls import path

from . import views
app_name="blog"

urlpatterns = [
    path('', views.index.as_view(), name="index"),
    path('home/', views.HomeView.as_view(), name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace="library"))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class SocialLink(models.Model):
    name = models.CharField(max_length=30)
    url = models.TextField()

    def __str__(self):
        return self.name

class TopicCategory(models.Model):
    title_english = models.CharField(max_length=100)
    title_other = models.CharField(max_length=100)
    short_description = models.TextField(max_length=200)
    image_name = models.CharField(max_length=50)

    YOUTUBE = 'YT'
    URL     = 'UR'
    topic_choice = (
        ('YT', 'Youtube'), 
        ('UR', "URL"),
    )

    topic_type = models.CharField(
        max_length=2,
        choices=topic_choice,
        default=YOUTUBE,
    )

    order = models.FloatField(default=0)

    def __str__(self):
        return self.title_english + " | " + self.title_other

class TopicContent(models.Model):
    topic_category = models.ForeignKey(
        'TopicCategory',
        on_delete = models.CASCADE,
    )
    title = models.CharField(max_length=200)
    description = models.TextField(default='', blank=True, null=True)
    video_id = models.CharField(max_length=20, blank=True, null=True)
    url = models.CharField(max_length=200, default=None, blank=True, null=True)
    tag = models.CharField(max_length=40, default=None, blank=True, null=True)
    order = models.FloatField(default=0)

    def __str__(self):
        return self.title

class SiteOption(models.Model):
    header = models.TextField(default='', blank=True, null=True)
    title  = models.CharField(max_length=200, default=None, blank=True, null=True)
    meta_author = models.CharField(max_length=100, default=None, blank=True, null=True)
    meta_description = models.TextField(default='', blank=True, null=True)

    def __str__(self):
        return "Customize frontend from admin panel"

blog/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import TemplateView
from .models import SocialLink
from .models import TopicCategory
from .models import TopicContent
from .models import SiteOption


class index(View):
    home = "index.html"
    def get(self, request):
        return render(request, self.home)

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        
        # Should be placed in all views in site
        context['social'] = SocialLink.objects.all().order_by('pk')
        context['site_option'] = SiteOption.objects.all()
        
        # Topic category and contents
        context['topic_category'] = TopicCategory.objects.all().order_by('order')

        for topic in context['topic_category']:
            topic.contents = TopicContent.objects.filter(topic_category=topic.id).order_by('order')

        # print(context['topic_category'])
        return context

blog/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{{ site_option.0.meta_description|default:"" }}">
    <meta name="author" content="{{ site_option.0.meta_author|default:"" }}">
    <link rel="icon" href="{% static 'img/favicons/favicon.ico' %}">

    <title>{{ site_option.0.title|default:"" }}</title>

    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'img/favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'img/favicons/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'img/favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">

    <link href="{% static 'css/ui.css' %}" rel="stylesheet">

    <!-- Facebook Open Graph -->
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="{{ site_option.0.title|default:"" }}" />
    <meta property="og:description" content="{{ site_option.0.meta_description|default:"" }}" />
    <meta property="og:image" content="{% static 'img/pythonbangla.jpg' %}" />


    <!-- Header section from admin panel -->
    {{ site_option.0.header|safe }}
</head>

<body>
    <div class="container">
        <header class="blog-header py-3">
            <div class="row flex-nowrap justify-content-between align-items-center">
                <!--
          <div class="col-4 pt-1">
            <a class="text-muted" href="#">Subscribe</a>
          </div> -->
                <div class="col-4 text-center">
                    <a class="blog-header-logo text-dark" href="/">
                        <img src="{% static 'img/logo.png' %}" alt="" height="80">
                    </a>
                </div>
            </div>
        </header>
        
        <div class="nav-scroller py-1 mb-2" style="overflow:hidden;">
                <div class="float-left"><nav class="nav">
                        <a class="p-2 text-muted" href="/">Home</a>
                    </nav></div>
                <div class="float-right">
                    <nav class="nav d-flex justify-content-end">
                        {% for s in social %}
                         <a class="p-2 text-muted" href="{{s.url}}" target="_blank"><img src="{% static 'img/social/icon-'%}{{s.name}}.png" alt="{{s.name|title}}" height="30"></a>
                        {% endfor %}
                    </nav>
                </div>
        </div>

        {% block content %}
        {% endblock %}
    </div>
    
    <div class="mb-4"></div>

    <footer class="blog-footer">
        <div class="row">
            <!-- <div class="col-sm-6">
                <p>
                    Developed by
                     <a href="" target="_blank">Ruckaiya</a> 
                    <br> © {% now "Y" as current_year %} {{ current_year }}
                    <a href="" target="_blank">Ruckaiya</a>
                </p>
            </div> -->
            <!-- <div class="col-sm-4">
                <p>Powered By <br>
                    <a href="https://www.djangoproject.com" target="_blank">Django</a> |
                    <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a> |
                    <a href="https://www.postgresql.org" target="_blank">PostgreSQL</a>
                    <br>
                    <a href="https://jquery.com/" target="_blank">JQuery</a> | 
                    <a href="https://github.com/cowboy/javascript-linkify" target="_blank">linkify</a>

                </p>
            </div> -->
            
            <div class="col-sm-12">
                <p>
                    <a href="#">Back to top</a>
                </p>
            </div>
        </div>
    </footer>
    
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="{% static 'js/vendor/holder.min.js' %}"></script>

    {% block script %}
    {% endblock %}
</body>
</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row mb-2">
{% for topic in topic_category %}
  <div class="col-md-6">
    <div class="card flex-md-row mb-4 box-shadow h-md-250">
      <div class="card-body d-flex flex-column align-items-start">
        <strong class="d-inline-block mb-2 color-gray">{{topic.title_english}}</strong>
        <h3 class="mb-0">
          <a id="id_{{topic.title_english|cut:' '}}" class="color{{ forloop.counter }}" href="#contents">{{topic.title_other}}</a>
        </h3>
        <div class="mb-2"></div>
        <p class="card-text mb-auto card-overflow">
        {{topic.short_description}}
        </p>
      </div>
      <img class="card-img-right flex-auto d-none d-lg-block" src="{% static 'img/cards/' %}{{topic.image_name}}" alt="{{topic.title_english}}">
    </div>
  </div>
{% endfor %}
</div>

<div id="contents" href="#"></div>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  {% for topic in topic_category %}
  <li class="nav-item">
      <a class="nav-link {% if forloop.counter == 1 %}active show{% endif %}" id="tab-{{ topic.title_english|cut:' ' }}" data-toggle="tab" href="#con-{{ topic.title_english|cut:' ' }}" role="tab" aria-controls="home"
        aria-selected="true">{{ topic.title_other }}</a>
  </li>
  {% endfor %}
</ul>

<div class="tab-content" id="myTabContent">
{% for topic in topic_category %}
  <div class="tab-pane fade {% if forloop.counter == 1 %}show active{% endif %}" id="con-{{ topic.title_english|cut:' ' }}" role="tabpanel" aria-labelledby="tab-{{ topic.title_english|cut:' ' }}">
      {% if topic.topic_type == 'YT' %}
      <!-- List & Videos Area -->
      <div class="video-border p-3 p-md-5 rounded-right rounded-bottom">
        <div role="tabpanel">
          <div class="row">
            <div class="col-4">
              <div class="list-group" id="list-tab" role="tablist">
                {% for tcontent in topic.contents %}
                <a class="list-group-item list-group-item-action {% if forloop.counter == 1 %} active show {% endif %}" id="list-home-list" data-toggle="tab" href="{{ tcontent.video_id }}" role="tab"
                  aria-controls="list-home" aria-selected="true">{{ tcontent.title }}{% if tcontent.tag %}<span style="display:block" class="badge text-primary">{{tcontent.tag}}</span>{% endif %}</a>
                  <span id="sdesc" class="d-none">{{ tcontent.description }}</span>
                {% endfor %}
              </div>
            </div>
            <!-- Youtube -->
            <div id="youtube-container" class="col-8">
              <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade active show" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
                  <div class="videoWrapper">
                    <iframe id="youtube-player-{{ topic.id }}" type="text/html" width="560" height="315" src="https://www.youtube.com/embed/{{topic.contents.0.video_id}}" frameborder="0"
                      allowfullscreen></iframe>
                  </div>
                  <div class="mb-3"></div>
                  <div id="youtube-description" class="youtube-description">
                      <pre style="white-space: pre-wrap;">{{topic.contents.0.description}}</pre>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% elif topic.topic_type == 'UR' %}
      <!-- Tutorial -->
      <ul class="list-group rounded">
          {% for tcontent in topic.contents %}
          <li class="list-group-item">
            <a href="{{ tcontent.url }}" target="_blank">{{ tcontent.title }}</a>
          </li>
          {% endfor %}
      </ul>
      <!-- End of Tutorial -->
      {% endif %}
  </div>
{% endfor %}
</div>

{% endblock content %}

{% block script %}
<script src="{% static 'js/ba-linkify.min.js' %}"></script>
<script>
  {% for topic in topic_category %}
  $("#id_{{topic.title_english|cut:' '}}").on('click', function (e) {
    var tabId = "#tab-{{topic.title_english|cut:' '}}"
    $(tabId).tab('show')
    /*
    $(".videoWrapper iframe").each(function(){
        // $(this).addClass("invisible")
        $(this).attr("class","invisible")
    }) */
    //$("#youtube-player-{{ topic.id }}").attr("class","visible")
  })
  {% endfor %}

  $(function(){
    $(".youtube-description pre").each(function(){
      $(this).html(linkify($(this).text()))
    })
  }) 

  $('#myTabContent #list-tab a').each(function (index) {
      $(this).on('click', function (e) {
          var href = $(this).attr('href')
          var newUrl = "https://www.youtube.com/embed/" + href
          $('#myTabContent .tab-pane:visible #youtube-container iframe').attr('src', newUrl)

          var videoDesc = $(this).next().text()
          videoDesc = linkify(videoDesc)
          $('#myTabContent .tab-pane:visible #youtube-description pre').html(videoDesc)
      })
  })

</script>
{% endblock script %}

blog/templates/index.html
{% load static %}

<html>
<head>
<title></title>  
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

</head>
<body>

  <div class="wrapper" 
        style="background: url(static/img/bg.jpg)
                no-repeat center center;
                background-size: cover;
                min-height: 40rem;">

    <nav id='menu'>

      <div class="logo">
          <a href=""><img src="{% static 'img/logo.png' %}" alt=""></a>
      </div>
          <input type='checkbox'/>
          <label>&#8801;</label>
          <ul>
      
          <li><a href='#'>About</a></li>
          <li><a href="{% url 'library:home' %}"> Library <font size='1'>&#9660;</font></a>
          <!-- <ul class='menus'>
          <li><a href='#'>Tab 1</a></li>
          <li><a href='#'>Tab 2</a></li>
          <li><a href='#'>Tab 3</a></li>
          <li><a href='#'>Tab 4</a></li>
          <li><a href='#'>Tab 5</a></li>
          <li><a href='#'>Tab 6</a></li>
          </ul> -->
          </li>
        
          <li><a href='#'>Others <font size='1'>&#9660;</font></a>
          <ul class='menus'>
          <li><a href='#'>Tab 1</a></li>
          <li><a href='#'>Tab 2</a></li>
          <li><a href='#'>Tab 3</a></li>
          </ul>
          </li>

          <li><a href="">Donate</a></li>
          <li><a href=""><i class="fas fa-user-plus"></i></a></li>
          </ul>
          </nav>
             
          <div class="intro">
            <h1>We ensure a better education</h1>
            <br>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab laboriosam eligendi placeat voluptatem modi numquam aliquam neque, et minima minus.</p>
            <br>  <br>
            <a href=""><button class="btn-1"> <a href="{% url 'library:home' %}"> START LEARNING</a></button></a>
          </div>
  </div>
         
                


<section class="services">
   <div class="container">
      <div class="row">
         <div class="col-md-12 col-sm-12"> 
           <div class="section-title">
             <h1>How Bangla Medium will work?</h1>
             <!-- <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce aliquet, massa ac ornare feugiat, 
                nunc dui auctor ipsum, sed posuere eros sapien id quam.
              </p> -->
           </div>
         </div><!-- .Col ends here -->
      </div><!-- .Row ends here -->
      <div class="row">
         <div class="col-md-3">
            <div class="service-thumb">
                <div class="thumb-icon"><i class="fa fa-paper-plane" aria-hidden="true"></i></div>
                <h4>Self-paced Learning</h4>
                <br>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit pellentesque.</p>
             </div>
         </div><!-- .Col ends here -->
         
         <div class="col-md-3">
            <div class="service-thumb">
                <div class="thumb-icon"><i class="fa fa-paint-brush" aria-hidden="true"></i></div>
                <h4>Develop sought-after skills</h4>
                <br>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit pellentesque.</p>
             </div>
         </div><!-- .Col ends here -->
         
         <div class="col-md-3">
            <div class="service-thumb">
                <div class="thumb-icon"><i class="fa fa-code" aria-hidden="true"></i></div>
                <h4>Virtual study groups</h4>
                <br>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit pellentesque.</p>
             </div>
         </div><!-- .Col ends here -->
         
         <div class="col-md-3">
            <div class="service-thumb">
                <div class="thumb-icon"><i class="fa fa-praying-hands" aria-hidden="true"></i></div>
                <h4>Variety of programs</h4>
                <br>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit pellentesque.</p>
             </div>
         </div><!-- .Col ends here -->
      </div><!-- .Row ends here -->
   </div><!-- .Container ends here -->
</section><!-- .Services ends here -->

<section>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-sm-12 col-12 join-title">
        <h1 class="text-center">Join Bangla Medium today </h1>
      </div>
     
      <div class="col-md-6 col-sm-12 col-12">
        <img src="{% static 'img/g.png' %}" alt="" class="image-fluid girl">
      </div>

      <div class="col-md-6 col-sm-12 boxes">
        <h2 class="text-center">as a ...</h2>
          <div class=" container button-container float-right">
              <a href="" class="ghost-button" target="_blank">Learner</a>
              <br/>
              <a href="" class="ghost-button">Teacher</a>
              <br/>
              <!-- Read the blog post -->
              <a href="" class="ghost-button" target="_blank">Parent</a>    
              <a href="" class="ghost-button" target="_blank">Sponsor</a>                            
          </div>
      </div>
    </div>
  </div>
</section>

<br> <br> <br> <br>

<footer>
  <div class="container">
    <div class="footer-top">
      <div class="row">
        <div class="col-md-6 col-lg about-footer">          
          <p>Our mission is to provide a free, world-class education to anyone, anywhere.
              <br>
              Bangla Medium is a nonprofit organization. <a href="">Donate</a> or <a href="">volunteer</a> today!</p>
          
          <ul class="footer__nav">
            <li><a href=""><i class="fa fa-envelope-open"></i>loremipsum@gmail.com</a></li>
            <li><a href=""><i class="fab fa-whatsapp"></i>+880-163-900-0921</a></li>
          </ul>
          <a href="" class="btn red-btn">Donate</a>
        </div>
        <div class="col-md-6 col-lg-3 page-more-info">
          <div class="footer-title">
            <h4>About</h4>
          </div>
          <ul class="footer__nav">
            <li><a href="">Our team</a></li>
            <li><a href="">Our content specialists</a></li>
            <li><a href="">Our leadership</a></li>
            <li><a href="">Our supporters</a></li>
          </ul>
        </div>

        <div class="col-md-6 col-lg-2 page-more-info">
          <div class="footer-title">
            <h4>Other Links</h4>
          </div>
          <ul class="footer__nav">
            <li><a href="">Careers</a></li>
            <li><a href="">Share your story</a></li>
            <li><a href="">Help center </a></li>
          </ul>
        </div>

        <div class="col-md-6 col-lg-2 page-more-info">
            <div class="footer-title">
              <h4>Courses</h4>
            </div>
            <ul class="footer__nav">
              <li><a href="">Computer Science</a></li>
              <li><a href="">Economics & Finance</a></li>
              <li><a href="">Arts & Humanities</a></li>
              <li><a href="">English</a></li>
              <li><a href="">Math & Science</a></li>
              <li><a href="">College, careers & more</a></li>
            </ul>
          </div>
      
        <div class="col-md-12 col-lg-12 open-hours">
          <div class="footer-title social">
            <h4>Connect With US</h4>
            <ul class="footer-social">
              <li><a href="" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
              <li><a href="" target="_blank"><i class="fab fa-twitter"></i></a></li>
              <li><a href="" target="_blank"><i class="fab fa-instagram"></i></a></li>
              <li><a href="" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>

            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-bottom">
      <div class="row">
        <div class="col-sm-4">
          <a href="">Privacy policy</a>
        </div>
        <div class="col-sm-8">
          <p>WE FOUNDATION BANGLADESH @ 2019 All rights reserved</p>
        </div>
      </div>
    </div>
  </div>
</footer>


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="{% static 'js/main.js' %}"></script>
</body>
</html>